---
title: "analyseSome"
author: "Alex Holcombe"
date: "7/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

```{r load file}
library(jsonlite)
dataDir<-"practiceData"
js<- fromJSON(file.path(dataDir,"alexh_28Jul2018_06-37authors.json"))
fileWithPath<- file.path(dataDir,"alexh_28Jul2018_06-37.txt")
df <-read_tsv(fileWithPath)  #read_tsv from tidyverse readr has advantage of not having padding spaces

```

Install skimr
```{r pressure, echo=FALSE}
#devtools::install_github("ropenscilabs/skimr")
#install.packages("tidyselect")  and from source to get 0.2.4 needed
library(skimr)
```

## Inspect data
```{r i, echo=FALSE}
skim(df)
```

Load ggplot and dplyr
```{r i, echo=FALSE}
library(ggplot2)
library(dplyr)
```

## Proportion correct

```{r i, echo=FALSE}
eachCorrect<- df %>% summarise_at(c("correct0","correct1"),mean)
avgCorrect = rowMeans(eachCorrect)
if (avgCorrect < .5) {
  shouldExclude = TRUE
}
practiceTrials = 3
df$experimentPhase<-NULL
df<- df %>% mutate(practice= trialnum<=2)
#Sanity check what ISIframes got to

longestISIframes<- max( df %>% filter(practice==0) %>% select("ISIframes") )

```
