---
title: "analyseAll"
author: "Alex Holcombe"
date: "7/28/2018"
output: html_document
---

Measurements Jen took for the monitors and viewing distance in OTC are Monitor height: 29.5cm, monitor length: 52.5cm, Viewing distance: 54cm.

I suppose I will combine all the js records into the tibble that also contains the data. After all, need some of those fields to know the condition.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data and improve column names

```{r load file, echo=FALSE}
#cat('Present directory is')
#print(getwd()))
rawDataPath<- file.path("dataRaw_notPutOnGitHubBecauseNotAnonymized")
#rawDataPath<- file.path("practiceData")
source(file.path("readInAllFiles.R"))

#loadOneSession("practiceData","bleo3225_01Aug2018_12-40.txt")
tbAll<- readInAllFiles(rawDataPath)

tbAll <- rename(tbAll, "firstReadLang" = "What is the first language you learned to read?")
tbAll <- rename(tbAll, "handedness" = "Which is your dominant hand for common tasks,\nlike writing, throwing, and brushing your teeth?\n\n")
tbAll$experimentPhase<-NULL

```

```{r excludeTutors}
tutors = list("bleo3225","ivan8836","cowe4014","bsze6874","ccha9074")
tbAll <- tbAll %>% filter( ! (subject %in% tutors) )
```

Anonymise subject names

```{r }
Ss <- unique(tbAll$subject)
listOfFakeNames <- 1:length(Ss)

#Permute to create random correspondence with codes
#Get a reproducible random seed so investigator can reverse to recover subject unikey if necessary
seed <- read_csv('subjectEncryptionKeyNotIndexedByGit/seed.csv')
seed <- seed$seed
set.seed(seed)
listOfFakeNames <- sample(listOfFakeNames)

#Replace real subject names by codes
#Create lookup table
lookup<- data.frame(old=Ss, new=listOfFakeNames)

newS <- tbAll$subject #new subject list
newS[] <- lookup$new[match(unlist(newS), lookup$old)] #https://stackoverflow.com/a/35636836/302378

tbAll$subject <- newS
tbAll$file <- NULL
```


Save data
```{r save file}
library(readr) #has better than save.csv https://readr.tidyverse.org/reference/write_delim.html
pathToSave <- file.path("dataAnonymized")
saveRDS(tbAll, file = file.path(pathToSave,"PSYC1anonymized.rda"), compress="bzip2")
write_csv(tbAll, file.path(pathToSave,"PSYC1anonymized.csv"))
```
